const router = require('express').Router();
const examController = require('../controller/examController');
router.post('/create', examController.createExam);
router.put('/update/:id', examController.updateExam);
router.delete('/delete/:id', examController.deleteExam);
router.delete('/delete_all', examController.deleteAll);
router.get('/:id/questions', examController.getQuestions);
router.post('/:id/push_question', examController.pushQuestion);
router.delete('/:id/delete_all_questions', examController.deleteAllQuestions);
router.get('/get_all', examController.getAllExams);
router.get('/:id', examController.getExam);
module.exports = router;